# 屏蔽取消操作
## awaitable asyncio.shield(aw, *, loop=None)
保护一个 可等待对象 防止其被 取消。

如果 aw 是一个协程，它将自动作为任务加入日程。

以下语句:
```
res = await shield(something())
```

相当于:
```
res = await something()
```
不同之处 在于如果包含它的协程被取消，在 something() 中运行的任务不会被取消。从 something() 的角度看来，取消操作并没有发生。然而其调用者已被取消，因此 "await" 表达式仍然会引发 CancelledError。

如果通过其他方式取消 something() (例如在其内部操作) 则 shield() 也会取消。

如果希望完全忽略取消操作 (不推荐) 则 shield() 函数需要配合一个 try/except 代码段，如下所示:

```
try:
    res = await shield(something())
except CancelledError:
    res = None
```